# Generated by Django 4.0.10 on 2023-06-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='Media/user_profile')),
                ('password', models.CharField(max_length=25)),
                ('otp', models.CharField(default='0000', max_length=25)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
